platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker
    tag: 24.0.7

inputs:
  - name: repo

outputs:
  - name: image

params:
  DOCKER_IMAGE_NAME: ""
  DOCKER_IMAGE_TAG: "latest"
  DOCKERFILE_PATH: "docker/"

run:
  path: sh
  args:
    - -exc
    - |
      cd repo
      echo "🛠 Build de l'image $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
      docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKERFILE_PATH
      docker save $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG > ../image/image.tar
