platform: linux

image_resource:
  type: registry-image
  source:
    repository: bitnami/kubectl
    tag: latest

inputs:
  - name: repo

params:
  KUSTOMIZE_PATH: kustomize/overlays/staging

run:
  path: sh
  args:
    - -exc
    - |
      kubectl apply -k repo/${KUSTOMIZE_PATH}
