platform: linux

image_resource:
  type: registry-image
  source:
    repository: maven
    tag: 3.8.6-openjdk-17

inputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      cd repo
      ./mvnw test
