image:
  tag: "1.27.0"
replicaCount: 3
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
autoscaling:
  targetCPUUtilizationPercentage: 50
ingress:
  hosts:
    - host: prod.demo.local
      paths:
        - path: /
          pathType: Prefix
redis:
  enabled: true
