default:
  tags:
    - $NOM_EQUIPE
  interruptible: true

image:
  name: docker-dev-virtual.repository.intra/maven/docker-pe-maven-3.8.6-jdk-17-owasp:1.0.0
  entrypoint:
    ["/bin/bash", "-c", "ln -snf /bin/bash /bin/sh && /bin/bash -c $0"]

.docker-service:
  services:
    - name: docker:20.10.16-dind
      # THIS IS IMPORTANT!
      command:
        [
          "--tls=false",
          "--registry-mirror",
          "https://docker-dev-virtual.repository.intra/",
          "--insecure-registry",
          "docker-dev-virtual.repository.intra",
          "--insecure-registry",
          "docker-outils-local.repository.intra",
        ]

include:
  - local: 'variables/defaults.yml'
  - local: 'templates/semantic-release.yml'
  - local: 'templates/sonar.yml'
  - local: 'templates/build-image.yml'
  - local: 'templates/deploy-environment.yml'
  - local: 'templates/test-mvn.yml'
  - local: 'templates/test-e2e.yml'
  - project: iam/secrets/conjur-secrets-gitlab-vals
    ref: v3.0.0
    file: gitlab/conjur_include.yml
  - project: devops/portfolio/front-portfolio-angular-e2e
    ref: master
    file: e2e-ci.yml

