apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-config
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  WELCOME_MESSAGE: {{ .Values.config.WELCOME_MESSAGE | quote }}
