apiVersion: v1
kind: Namespace
metadata:
  name: namespace-final
  annotations:
    equipe: henriFrank
  labels:
    app: namespace-final
    composant: namespace-final

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: namespace-final
  annotations:
    contact-en-cas-d-urgence: _ldr_si_henriFrank@home.fr
    equipe: henriFrank
    projet-gitlab:  https://git-scm.home.intra/henriFrank/gxx/gxx-tools/sondes-henriFrank.git
    composant: uptime-kuma
    technologie: bouchon
  labels:
    app: uptime-kuma
    composant: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
        composant: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: /app/data
              name: data
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 64Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: namespace-final
  annotations:
    contact-en-cas-d-urgence: _ldr_si_henriFrank@home.fr
    equipe: henriFrank
    projet-gitlab:  https://git-scm.home.intra/henriFrank/gxx/gxx-tools/sondes-henriFrank.git
    composant: uptime-kuma
    technologie: bouchon
  labels:
    app: uptime-kuma
    composant: uptime-kuma
spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  namespace: namespace-final
  annotations:
    contact-en-cas-d-urgence: _ldr_si_henriFrank@home.fr
    equipe: henriFrank
    projet-gitlab:  https://git-scm.home.intra/henriFrank/gxx/gxx-tools/sondes-henriFrank.git
    composant: uptime-kuma
    technologie: bouchon
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: certificat-ingress-issuer
  labels:
    app: uptime-kuma
    composant: uptime-kuma
spec:
  rules:
    - host: uptime-kuma.cluster-final-bdx.k8s.home.intra
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: namespace-final
  annotations:
    contact-en-cas-d-urgence: _ldr_si_henriFrank@home.fr
    equipe: henriFrank
    projet-gitlab:  https://git-scm.home.intra/henriFrank/gxx/gxx-tools/sondes-henriFrank.git
    composant: uptime-kuma
    technologie: bouchon
  labels:
    app: uptime-kuma
    composant: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
