apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ingress.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      code-composant: xx666
      sous-composant: lighthouse-report-server-gxx


commonAnnotations:
  quartierPos: Gestion_SI
  equipe: henriFrank
  contact-en-cas-d-urgence: _ldr_si_henriFrank@home.fr
  projet-gitlab: https://git-scm.home.intra/henriFrank/gxx/tools/lighthouse-server
  bloc-pos: gssi
  ucd: gouvernance-architecture-applicative
  oneagent.dynatrace.com/inject: "false" # Permet d'exclure de l'instrumentation dynatrace
