apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: gouvernance-architecture-applicative-va


patches:
- target:
    group: networking.k8s.io
    kind: Ingress
    name: lhci-ingress
    version: v1
  path: ingress-patch.yaml
