# Utiliser l'image de base patrickhulce/lhci-server
FROM patrickhulce/lhci-server

# Installation des dépendances supplémentaires nécessaires pour exécuter lhci
RUN npm install -g @lhci/cli

# Exposez le port du serveur Lighthouse CI
EXPOSE 9001
